### ISSUE TITLE
default imports do not work with TypeScript 

### ISSUE THREAD

**Issue by khol341** [fastify/fastify-auth#107]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.x

### Plugin version

1.1.0

### Node.js version

14.x

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

When trying to use this import in TS using the [latest fastify-auth version](https://github.com/fastify/fastify-auth/releases/tag/v1.1.0):

```
import fastifyAuth from 'fastify-auth';
app
    .register(fastifyJwt, { secret: 'secret' })
    .register(fastifyAuth)
```
, it actually doesn't work anymore and throws an error:
`error TS2339: Property 'auth' does not exist on type 'FastifyInstance'.` This is not a problem when using [the older version](https://github.com/fastify/fastify-auth/releases/tag/v1.0.1).

I see a similar issue was posted for fastify-jwt [here](https://github.com/fastify/fastify-jwt/issues/150) which still replicates.

### Steps to Reproduce

Try to import plugin using named import in TypeScript.

### Expected Behavior

Named import should work.

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by climba03003** [comment]
Please use `esModuleInterop` for `tsconfig.json`.

```json
{
  "compilerOptions": {
    "esModuleInterop": true,
  }
}
```

**Comment by mmarkell** [comment]
@climba03003 that does not fix the issue. Still getting the same error.

**Comment by climba03003** [comment]
> @climba03003 that does not fix the issue. Still getting the same error.

Please provide a repro for your issue. TypeScript behave differently depends on version, how you use and configuration.
