### ISSUE TITLE
Ability to customize the decorator name

### ISSUE THREAD

**Issue by paulorodrigues-mb** [fastify/fastify-auth#136]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

The ability to customize the decorator name, we can keep `auth` as default, but would be nice to have a way to change this via server options.

May I do my first fastify related PR or do you guys think not worth it?

Thank you!

### Motivation

I already have an `auth` decorator on my application.

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by paulorodrigues-mb** [comment]
Yes I do, thanks!
