### ISSUE TITLE
How to pass user object to route handler

### ISSUE THREAD

**Issue by robinvdvleuten** [fastify/fastify-auth#16]
When an user is successfully authenticated, how can I pass the user to the route handler?

**Comment by delvedor** [comment]
Hi!
You can decorate the request instance with a `user` key, and then assign it the user object.

For example:
```js
fastify.decorateRequest('user', null)

fastify.addHook('preHandler', async (req, reply) => {
  const user = await yourAuth(req)
  req.user = user
})

fastify.get('/', async (req, reply) => {
  req.log.info(req.user)
  return 'ok'
})
```

**Comment by Nisthar** [comment]
> ```js
> fastify.addHook('preHandler', async (req, reply) => {
>   const user = await yourAuth(req)
>   req.user = user
> })
> ```

using this code you don't need to use this library Right?
