### ISSUE TITLE
NPM package update

### ISSUE THREAD

**Issue by buzzik** [fastify/fastify-auth#199]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Latest npm package version still is 4.2.0
But you did important fix in 4.3.0 when we can expect this package to be published to npm?

**Comment by Uzlopak** [comment]
@mcollina

**Comment by mcollina** [comment]
done

**Comment by buzzik** [comment]
@mcollina thank you!

**Comment by climba03003** [comment]
Seems like I messed up with my environment again.
