### ISSUE TITLE
Using multiple strategies does not work

### ISSUE THREAD

**Issue by vorillaz** [fastify/fastify-auth#22]
Hey, thanks for the lovely work.
I was playing around with `fastify-auth` and I can't actually create a steady case with multiple strategies. Apparently, something does not work as expected. Using the example below the authentication flow does not pass by `bar()` strategy.

```javascript
const Fastify = require('fastify');

const build = (opts = {}) => {
  const fastify = Fastify(opts);
  const routes = () => {
    fastify.get(
      '/',
      {
        beforeHandler: fastify.auth([fastify.foo, fastify.bar])
      },
      (request, reply) => ({hello: 'world'})
    );
  };
  return fastify
    .register(require('fastify-auth'))
    .decorate('foo', (req, rep, done) => {
      console.log('foo');
      done();
    })
    .decorate('bar', (req, rep, done) => {
      console.log('bar');
      done();
    })
    .after(routes);
};

const fastify = build();
fastify.listen(3000, err => {
  if (err) throw err;
  console.log(`Server listenting at http://localhost:${fastify.server.address().port}`);
});
```

Any help will be highly appreciated.

**Comment by delvedor** [comment]
Hello! From the docs:

> fastify-auth will run all your authentication methods if at least one succeed it will continue your request, otherwise it will return an error to the client. It will automatically stop as soon as a authentication succeed.

Since you are not passing an error to the done callback the authentication is considered successful at the first step.

**Comment by aalfiann** [comment]
Hello, I've having same issue.

But I use async function, so there is no done callback, so how to solve this?

**Comment by aalfiann** [comment]
Hey, I got  it works now with using `{ run: 'all' }`

Sorry, to disturb..
