### ISSUE TITLE
How about an option for auth in parallel or serial?

### ISSUE THREAD

**Issue by poppinlp** [fastify/fastify-auth#27]
I may wanna check auth in order in some cases. And in other cases it could be run in parallel, and in this way i may get a faster response by an auth cache maybe. :)

**Comment by mcollina** [comment]
What happens if one of the functions errors, but another one authenticate the user? Who wins?

I fear a parallel strategy might be less secure, because of potential edge cases.

I’m happy to review a PR anyway

**Comment by poppinlp** [comment]
In my opinion, the parallel strategy should be success if one of the functions pass and fail if all of the functions errors.
We should write it down in doc to tell people about the secure risk of this strategy.
In some case, such as the auth token could come from different ways like request header, query param, cookie e.t.c which are standalone, we could do the authentication in parallel.

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by poppinlp** [comment]
OK. I'll do it this weekend.

**Comment by Eomm** [comment]
This has been done by the `relation` param 👍
