### ISSUE TITLE
fasttify.auth stalled in jwt verify

### ISSUE THREAD

**Issue by mandaputtra** [fastify/fastify-auth#29]
I'm using fastify-jwt to verify JWT but. but when i combine it with fastify-auth the auth method just stalled and i did not get any response. what could go wrong?

my server.js
```JavaScript
const fastify = require("fastify")({
  logger: {
    prettyPrint: true,
    prettifier: require('pino-pretty')
  }
});

fastify
  .register(require('fastify-cors'), {
    origin: true
  })
  .register(require("./plugins/db"), {
    url: "mongodb://localhost:27017/vfcms"
  })
  .register(require('fastify-jwt'), {
    secret: 'supersecret',
    maxAge: '1d'
  })
  .register(require('fastify-auth'))

  fastify.decorate('verifyJWT', async (req, reply) => {
    try {
      await req.jwtVerify()
    } catch (error) {
      reply.send(error)
    }
  })

fastify.register(require("./services/root"));
fastify.register(require("./services/user"));

fastify.listen(3000, function(err, address) {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
  fastify.log.info(`server listening on ${address}`);
});

```

my root.js
```JavaScript
async function routes(fastify, options) {
  fastify.route({
    method: 'GET',
    url: '/',
    handler: (req, reply) => {
      reply.code(200).send({ api: "ready"})
    }
  })

  fastify.route({
    method: 'GET',
    url: '/dashboard',
    beforeHandler: fastify.auth([
      fastify.verifyJWT
    ]),
    handler: (req, reply) => {
      reply.code(200).send({ imVerified: "ready"})
    }
  })
}

module.exports = routes;
```
a complete repo my project are on [github](https://github.com/mandaputtra/vf-cms).

but if I'm not using `beforeHandler: fastify.auth([ fastify.verifyJWT ])` and just `beforeHandler: [ fastify.verifyJWT ]` it pass perfectly, any advice?

**Comment by mcollina** [comment]
Do you need multiple auth strategies? If not, you won’t need fastify-auth.

**Comment by mcollina** [comment]
In fastify-auth, every auth function must have a third parameter (done) to signal fastify-auth that auth strategy was completed. See https://github.com/fastify/fastify-auth/blob/master/README.md for details.

**Comment by mandaputtra** [comment]
Ups! Thanks

**Comment by Akiyamka** [comment]
I have same problem. If a have some async action, server not response at all.
```
  fastify.decorate('verifyJWT', (request, reply, done) => {
    request.jwtVerify()
      .then(token => {
        console.log('TOKEN')
        done()
      })
      .catch(error => {
        console.log('error')
        done(error)
      });
```
I see `error` in log, but server not create any response. Browser still pending.

**Comment by mcollina** [comment]
I don't understand your problem @Akiyamka. Please open a new issue in https://github.com/fastify/help as this is likely not to be an issue with this module.

**Comment by VarunBatraIT** [comment]
> I have same problem. If a have some async action, server not response at all.
> 
> ```
>   fastify.decorate('verifyJWT', (request, reply, done) => {
>     request.jwtVerify()
>       .then(token => {
>         console.log('TOKEN')
>         done()
>       })
>       .catch(error => {
>         console.log('error')
>         done(error)
>       });
> ```
> 
> I see `error` in log, but server not create any response. Browser still pending.

Don't use done() when there is no error with async or promise.
