### ISSUE TITLE
New parameter: run all

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify-auth#61]
## 🚀 Feature Proposal

Add a new parameter to execute all the auth handler in any case.

Right now if the relation is `or` it will stop at the first success if it is `and` it will stop at the first error.

## Motivation

The user may want to get all the info from the request and act accordingly in the `setErrorHandler` function.
In my case, I have a request with many tokens and I need to parse them all

## Example

```js
fastify.route({
      method: 'POST',
      url: '/auth-multiple',
      preHandler: fastify.auth([
        fastify.verifyAdmin,
        fastify.verifyReputation
      ], {
        relation: 'and',
        run: 'all'
      }),
      handler: (req, reply) => {
        req.log.info('Auth route')
        reply.send({ hello: 'world' })
      }
})
```

**Comment by mcollina** [comment]
Go for it!

Il giorno mar 19 nov 2019 alle ore 11:59 Manuel Spigolon <
notifications@github.com> ha scritto:
