### ISSUE TITLE
Proposal - Provide a better and modular auth mechanism

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify-auth#8]
Hi, I just found this plugin and would like to know how can it help me to implement an auth mechanism in my application but I'm a little bit confused

> This module does not provide an authentication strategy, but it provides a very fast utility to handle authentication (also multiple strategies) in your routes, without adding overhead.

Marketing boom!

The documentation is really complex and it is hard to find an intro. In my opinion, it looks like that this plugin only helps to run an array of auth functions and respond with 401 when an error was passed. I really expect something different when I read `fastify-auth`. This is just my personal feedback and as always I'm engaged to help you with that.

It would be great to provide an interface to implement different auth strategys similiar to hapi so that the implementation details are not visible for the route definition.

```js
fastify.route({
      method: 'POST',
      auth: 'basic',
      url: '/auth',
      handler: ....
})
```

### Proposal:
- Create an `onAddRoute` hook to build the `beforeHandler` for the specific auth strategy at startup time.

```js
function fastifyAuth(fastify, opts, done) {
 fastify.addHook('onAddRoute', (route, done) => {
   if(opts.auth === 'basic') {
     route.beforeHandler.add(require('fastify-basic-auth'))
   }
   done()
 })
}
```

**Comment by mcollina** [comment]
That can be a good idea. how about you open an issue on the main repo?

**Comment by StarpTech** [comment]
https://github.com/fastify/fastify/issues/605

**Comment by StarpTech** [comment]
`onRoute` was merged. We could discuss a better abstraction.

**Comment by mcollina** [comment]
Yes we should! Would you mind in flashing out what the code would look like with onRoute?
