### ISSUE TITLE
Provide a way to skip an auth handler

### ISSUE THREAD

**Issue by cliedeman** [fastify/fastify-auth#81]
## 🚀 Feature Proposal

Allow an auth handler to inform the plugin the this auth does not apply and skip to the next handler (if any)

## Motivation
Creating an abitrary error is clunky and hard to read

From sample repo: https://github.com/cliedeman/fastify-anonymous-example/blob/master/src/app.ts#L40
```
  await app.decorate(
    'allowAnonymous',
    function (
      request: FastifyRequest,
      _reply: FastifyReply,
      done: DoneFuncWithErrOrRes
    ) {
      if (!request.headers.authorization) {
        return done();
      }

      // Noisy Error
      return done(new Error('not anonymous'));
    }
  );

  await app.decorate(
    'allowBearerAuth',
    function (
      request: FastifyRequest,
      _reply: FastifyReply,
      done: DoneFuncWithErrOrRes
    ) {
      if (request.headers.authorization) {
        ...
        return done();
      }

      // Noisy Error
      return done(new Error('anonymous'));
    }
  );
```

Please provide an example for how this feature would be used.

```
import {default as fastifyAuth, errNextAuth } from 'fastify-auth';

...

  await app.decorate(
    'allowAnonymous',
    function (
      request: FastifyRequest,
      _reply: FastifyReply,
      done: DoneFuncWithErrOrRes
    ) {
      if (!request.headers.authorization) {
        return done();
      }

      return done(errNextAuth);
    }
  );

  await app.decorate(
    'allowBearerAuth',
    function (
      request: FastifyRequest,
      _reply: FastifyReply,
      done: DoneFuncWithErrOrRes
    ) {
      if (request.headers.authorization) {
        ...
        return done();
      }

      return done(errNextAuth);
    }
  );
```

This will also allow the plugin to report a different error if no handler accepted the request.

**Comment by Eomm** [comment]
Do you mean a sort of `precondition: function()` that must be met to run the auth function itself?

**Comment by cliedeman** [comment]
@Eomm that is one possible solution. Essentially a way for the auth function to say this request is not applicable. 

Contrived Example:
Basic auth handler skipers requests where the Authorization header does not start with `Basic `

**Comment by mcollina** [comment]
Why using an error is considered clunky/noisy? What impact does it have?

**Comment by cliedeman** [comment]
> Why using an error is considered clunky/noisy? What impact does it have?

firstly its personal opinion. I like the code to be more uniform instead of making users create a custom error/message in each function

I would probably do something along these lines
```
/// Indicates the auth handler did not fail but is not applicable to request
class SkipAuthError extends Error {
    constructor(m: string) {
        super(m);
        Object.setPrototypeOf(this, SkipAuthError.prototype);
    }
}

return done(new SkipAuthError("Basic Auth Skipped"));
```

Secondly there is a _slight_ performance benefit to not creating a new error on each invocation and instead using a sentinal value.

**Comment by mcollina** [comment]
My concern in using a non `Error` value is that `Fastify` itself does not understand it. This means the defined functions would need to be specific to fastify-auth, which is something we are trying to avoid in the overall ecosystem.

As an example, https://github.com/fastify/fastify-auth/blob/master/example-async.js#L29-L33 already has an Error. I don't see how this would improve this module.

**Comment by cliedeman** [comment]
> My concern in using a non Error value is that Fastify itself does not understand it

`errNextAuth` should definitely be an error. Something along the lines of 

```js
class ErrorNextAuth extends Error {
  constructor() {
    super("Auth Skipped");
    this.name = 'ErrorNextAuth';
  }
}

const errNextAuth = new ErrorNextAuth();
```

> As an example, https://github.com/fastify/fastify-auth/blob/master/example-async.js#L29-L33 already has an Error. I don't see how this would improve this module.

The core use case would be making auth handlers uniform and giving them an escape hatch. For example when logging failures some information is lost.

What we will see when using the plugin is that the last auth handler in the chain failed. (possibly with an unrelated message)

```
if (!request.raw.headers.auth) {
      return Promise.reject(new Error('Missing token header'))
    }
```

where instead I would want to know that none of the auth handlers accepted the given request.
This missing token header rejection coud be a real error or covered up by different rejection later in the auth chain.

**Comment by mcollina** [comment]
A few comments above, you said

> Secondly there is a slight performance benefit to not creating a new error on each invocation and instead using a sentinal value.

Using an Error object from fastify-auth in fastify-jwt would not really work as you'd have an import/require loop, and potentially two different implementation of the same class.

Maybe we could use a property? if `authSkipped` is set to `true`, it does something?

**Comment by cliedeman** [comment]
> Using an Error object from fastify-auth in fastify-jwt would not really work as you'd have an import/require loop, and potentially two different implementation of the same class.

I'm not sure I follow. I add fastify-jwt to my example

https://github.com/cliedeman/fastify-anonymous-example/blob/example/error/src/app.ts#L45

> Maybe we could use a property? if authSkipped is set to true, it does something?

I think that is simliar to what @Eomm suggested.
but that change felt more invasive and I thought we could get away with something simpler.

Do you mean something along these lines?

```
export type FastifyAuthFunction = (
  request: FastifyRequest,
  reply: FastifyReply,
  done: (error?: Error) => void
) => void;

export type FastifyAuthSkipFunction = (
  request: FastifyRequest,
  reply: FastifyReply
) => bool;

declare module 'fastify' {
  interface FastifyInstance {
    auth(
      functions: Array<{fn: FastifyAuthFunction, skip?:FastifyAuthSkipFunction }>[],
      options?: {
        relation?: 'and' | 'or',
        run?: 'all'
      }
    ): preHandlerHookHandler;
  }
}
```

**Comment by mcollina** [comment]
I mean:

```js
const err = new Error('skip auth')
err.skipAuth = true
```

I'm also ok in what @eomm proposed and you described in https://github.com/fastify/fastify-auth/issues/81#issuecomment-776546016
